token: "secret"

cronjobs:
  - name: "test"
    pattern: "0 0 * * *"
    endpoint: "http://localhost:3000/api/cron/cleanup"
    data:
      foo: "bar"

queues:
  - name: "test"
    endpoint: "http://localhost:3000/api/queue/test"
